//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Interface.Server.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomersRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomersRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Interface.Server.Resources.Localization.CustomersRes", typeof(CustomersRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact title.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select post code.
        /// </summary>
        public static string Customer_SelecPostCode {
            get {
                return ResourceManager.GetString("Customer_SelecPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        public static string Customer_SelectCity {
            get {
                return ResourceManager.GetString("Customer_SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        public static string Customer_SelectCountry {
            get {
                return ResourceManager.GetString("Customer_SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select title.
        /// </summary>
        public static string Customer_SelectTitle {
            get {
                return ResourceManager.GetString("Customer_SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer title.
        /// </summary>
        public static string CustomerTitle {
            get {
                return ResourceManager.GetString("CustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered address.
        /// </summary>
        public static string EnterdAddress {
            get {
                return ResourceManager.GetString("EnterdAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered contact name.
        /// </summary>
        public static string EnterdContactName {
            get {
                return ResourceManager.GetString("EnterdContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered company name.
        /// </summary>
        public static string EnterСompanyName {
            get {
                return ResourceManager.GetString("EnterСompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vip.
        /// </summary>
        public static string IsVip {
            get {
                return ResourceManager.GetString("IsVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected customer title.
        /// </summary>
        public static string SelectCustomerTitle {
            get {
                return ResourceManager.GetString("SelectCustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select customer title.
        /// </summary>
        public static string Selectec_CustomerTitle {
            get {
                return ResourceManager.GetString("Selectec_CustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected city.
        /// </summary>
        public static string SelectedCity {
            get {
                return ResourceManager.GetString("SelectedCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected country.
        /// </summary>
        public static string SelectedCountry {
            get {
                return ResourceManager.GetString("SelectedCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected post code.
        /// </summary>
        public static string SelectedPostCode {
            get {
                return ResourceManager.GetString("SelectedPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
