//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Interface.Server.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsersAdmRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsersAdmRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Interface.Server.Resources.Localization.UsersAdmRes", typeof(UsersAdmRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email is already registered.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length password 6 symbols.
        /// </summary>
        public static string MinLengthPassword6Symbols {
            get {
                return ResourceManager.GetString("MinLengthPassword6Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comferm password.
        /// </summary>
        public static string Password_C {
            get {
                return ResourceManager.GetString("Password_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select role.
        /// </summary>
        public static string Selectec_Role {
            get {
                return ResourceManager.GetString("Selectec_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have at least one letter.
        /// </summary>
        public static string StringMustContainOneLater {
            get {
                return ResourceManager.GetString("StringMustContainOneLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one capital letter.
        /// </summary>
        public static string StringMustContainUpperLater {
            get {
                return ResourceManager.GetString("StringMustContainUpperLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered correct Email.
        /// </summary>
        public static string UserAdm_Email_EmailAddress {
            get {
                return ResourceManager.GetString("UserAdm_Email_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Email.
        /// </summary>
        public static string UserAdm_Email_Required {
            get {
                return ResourceManager.GetString("UserAdm_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length 50 symbols.
        /// </summary>
        public static string UserAdm_Email_StringLength {
            get {
                return ResourceManager.GetString("UserAdm_Email_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered name.
        /// </summary>
        public static string UserAdm_FirstName_Required {
            get {
                return ResourceManager.GetString("UserAdm_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered surname.
        /// </summary>
        public static string UserAdm_LastName_Required {
            get {
                return ResourceManager.GetString("UserAdm_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered password.
        /// </summary>
        public static string UserAdm_Password_Required {
            get {
                return ResourceManager.GetString("UserAdm_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password must match.
        /// </summary>
        public static string UserAdm_PasswordComferm_Comparer {
            get {
                return ResourceManager.GetString("UserAdm_PasswordComferm_Comparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected role.
        /// </summary>
        public static string UserAdm_RoleID_Range {
            get {
                return ResourceManager.GetString("UserAdm_RoleID_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected role.
        /// </summary>
        public static string UserAdm_RoleID_Required {
            get {
                return ResourceManager.GetString("UserAdm_RoleID_Required", resourceCulture);
            }
        }
    }
}
